spring.application.name=rccms-app
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/mh_rccms
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

rccms.admin.user-id=admin
rccms.admin.password=admin@123
rccms.jwt.secret=VGhpc0lzQVNpbXBsZVJhbmRvbVNlY3JldEtleUZvclJDQ01TSldUQXV0aA==
rccms.jwt.expiry-ms=86400000
rccms.cors.allowed-origins=http://localhost:4200
